### ISSUE TITLE
undefined method `shelljoin' for nil:NilClass when upgrade to emacs-26.1-z-mac-7.4

### ISSUE THREAD

**Issue by lukertty** [railwaycat/homebrew-emacsmacport#153]
## Environment
* 10.12.6 (16G1618)
* latest homebrew and emacs
## build options
```
Upgrading railwaycat/emacsmacport/emacs-mac --with-modules --with-xml2 --with-natural-title-bar --without-gnutls --with-glib --with-imagemagick
```
## backtrace
```
==> Applying emacs-mac-title-bar.patch
patch -g 0 -f -p1 -i /private/tmp/emacs-mac--patch-20181117-99790-1m4yn5/emacs-mac-title-bar.patch
patching file src/macappkit.m
Hunk #1 succeeded at 2098 (offset 24 lines).
Hunk #2 FAILED at 2596.
Hunk #3 succeeded at 6457 (offset 417 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/macappkit.m.rej
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/bin/ebrowse ebrowse
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/bin/emacs emacs
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/bin/emacs-26.1 emacs-26.1
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/bin/emacsclient emacsclient
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/bin/etags etags
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/appdata appdata
mkdir -p /usr/local/share/applications
ln -s ../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/applications/emacs.desktop emacs.desktop
ln -s ../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/emacs/26.1 26.1
ln -s ../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/emacs/site-lisp/subdirs.el subdirs.el
mkdir -p /usr/local/share/icons
mkdir -p /usr/local/share/icons/hicolor
mkdir -p /usr/local/share/icons/hicolor/128x128
mkdir -p /usr/local/share/icons/hicolor/128x128/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/128x128/apps/emacs.png emacs.png
mkdir -p /usr/local/share/icons/hicolor/16x16
mkdir -p /usr/local/share/icons/hicolor/16x16/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/16x16/apps/emacs.png emacs.png
mkdir -p /usr/local/share/icons/hicolor/24x24
mkdir -p /usr/local/share/icons/hicolor/24x24/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/24x24/apps/emacs.png emacs.png
mkdir -p /usr/local/share/icons/hicolor/32x32
mkdir -p /usr/local/share/icons/hicolor/32x32/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/32x32/apps/emacs.png emacs.png
mkdir -p /usr/local/share/icons/hicolor/48x48
mkdir -p /usr/local/share/icons/hicolor/48x48/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/48x48/apps/emacs.png emacs.png
mkdir -p /usr/local/share/icons/hicolor/scalable
mkdir -p /usr/local/share/icons/hicolor/scalable/apps
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/scalable/apps/emacs.svg emacs.svg
mkdir -p /usr/local/share/icons/hicolor/scalable/mimetypes
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/scalable/mimetypes/emacs-document.svg emacs-document.svg
ln -s ../../../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/icons/hicolor/scalable/mimetypes/emacs-document23.svg emacs-document23.svg
ln -s ../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/info/emacs emacs
ln -s ../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/man/man1/ebrowse.1.gz ebrowse.1.gz
ln -s ../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/man/man1/emacs.1.gz emacs.1.gz
ln -s ../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/man/man1/emacsclient.1.gz emacsclient.1.gz
ln -s ../../../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/share/man/man1/etags.1.gz etags.1.gz
ln -s ../Cellar/emacs-mac/emacs-26.1-z-mac-7.3/lib/systemd systemd
Error: undefined method `shelljoin' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:539:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:743:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:163:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:109:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

Any ideas? Thanks

**Comment by lululau** [comment]
It should have been fixed in this PR: https://github.com/railwaycat/homebrew-emacsmacport/pull/154

**Comment by lukertty** [comment]
Thanks~
